# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_populate_schedulemetadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulemetadata',
            options={'ordering': ['sin', 'name']},
        ),
        migrations.AddField(
            model_name='contract',
            name='keywords',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='certifications',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
