# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-22 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_populate_schedulemetadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulemetadata',
            options={'ordering': ['sin', 'name']},
        ),
    ]
