# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_auto_20190904_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
