# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='security_clearance',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
