# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0018_submittedpricelistrow_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='capability_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=2500)),
            ],
        ),
    ]
