# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0019_capability_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpricelistrow',
            name='security_clearance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
